/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'upaulm2' at '5/9/18 3:48 PM' with Gradle 3.1
 *
 * @author upaulm2, @date 5/9/18 3:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
