/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'upaulm2' at '5/9/18 3:48 PM' with Gradle 3.1
 *
 * @author upaulm2, @date 5/9/18 3:48 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
